# Generated by Django 4.2.11 on 2024-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
